<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Achievement;
use App\Models\FinancialQuest;

class GamificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $achievements = [
            [
                'slug'           => 'first_tx',
                'title'          => 'Pencatat Pemula',
                'description'    => 'Catat transaksi pertama Anda di MoneFin.',
                'category'       => 'transaction',
                'tier'           => 'bronze',
                'xp_reward'      => 50,
                'icon'           => 'Zap',
                'required_count' => 1,
            ],
            [
                'slug'           => 'tx_10',
                'title'          => 'Pencatat Aktif',
                'description'    => 'Catat minimal 10 transaksi pengeluaran/pemasukan.',
                'category'       => 'transaction',
                'tier'           => 'bronze',
                'xp_reward'      => 100,
                'icon'           => 'Zap',
                'required_count' => 10,
            ],
            [
                'slug'           => 'tx_50',
                'title'          => 'Pakar Arus Kas',
                'description'    => 'Catat minimal 50 transaksi di dalam aplikasi.',
                'category'       => 'transaction',
                'tier'           => 'silver',
                'xp_reward'      => 250,
                'icon'           => 'Zap',
                'required_count' => 50,
            ],
            [
                'slug'           => 'tx_100',
                'title'          => 'Legenda Finansial',
                'description'    => 'Catat minimal 100 transaksi secara konsisten.',
                'category'       => 'transaction',
                'tier'           => 'gold',
                'xp_reward'      => 500,
                'icon'           => 'Zap',
                'required_count' => 100,
            ],
            [
                'slug'           => 'streak_3',
                'title'          => 'Percikan Disiplin',
                'description'    => 'Pertahankan streak pencatatan selama 3 hari berturut-turut.',
                'category'       => 'streak',
                'tier'           => 'bronze',
                'xp_reward'      => 75,
                'icon'           => 'Flame',
                'required_count' => 3,
            ],
            [
                'slug'           => 'streak_7',
                'title'          => 'Pejuang Mingguan',
                'description'    => 'Pertahankan streak pencatatan selama 7 hari berturut-turut.',
                'category'       => 'streak',
                'tier'           => 'silver',
                'xp_reward'      => 150,
                'icon'           => 'Flame',
                'required_count' => 7,
            ],
            [
                'slug'           => 'streak_30',
                'title'          => 'Konsistensi Bulanan',
                'description'    => 'Pertahankan streak pencatatan selama 30 hari tanpa terputus.',
                'category'       => 'streak',
                'tier'           => 'gold',
                'xp_reward'      => 400,
                'icon'           => 'Flame',
                'required_count' => 30,
            ],
            [
                'slug'           => 'streak_100',
                'title'          => 'Grandmaster Habit',
                'description'    => 'Capai 100 hari streak pencatatan legendaris.',
                'category'       => 'streak',
                'tier'           => 'platinum',
                'xp_reward'      => 1000,
                'icon'           => 'Flame',
                'required_count' => 100,
            ],
            [
                'slug'           => 'first_goal',
                'title'          => 'Perancang Impian',
                'description'    => 'Buat target tabungan pertama Anda.',
                'category'       => 'saving',
                'tier'           => 'bronze',
                'xp_reward'      => 50,
                'icon'           => 'Target',
                'required_count' => 1,
            ],
            [
                'slug'           => 'first_deposit',
                'title'          => 'Langkah Awal Menabung',
                'description'    => 'Lakukan deposit pertama ke target tabungan Anda.',
                'category'       => 'saving',
                'tier'           => 'bronze',
                'xp_reward'      => 50,
                'icon'           => 'Target',
                'required_count' => 1,
            ],
            [
                'slug'           => 'goal_completed_1',
                'title'          => 'Penakluk Target',
                'description'    => 'Capai 100% dari salah satu target tabungan Anda.',
                'category'       => 'saving',
                'tier'           => 'silver',
                'xp_reward'      => 200,
                'icon'           => 'Target',
                'required_count' => 1,
            ],
            [
                'slug'           => 'goal_completed_3',
                'title'          => 'Wirausahawan Impian',
                'description'    => 'Berhasil menyelesaikan 3 target tabungan impian.',
                'category'       => 'saving',
                'tier'           => 'gold',
                'xp_reward'      => 500,
                'icon'           => 'Target',
                'required_count' => 3,
            ],
            [
                'slug'           => 'security_2fa',
                'title'          => 'Benteng Keamanan',
                'description'    => 'Aktifkan Two-Factor Authentication (2FA) untuk perlindungan akun.',
                'category'       => 'security',
                'tier'           => 'silver',
                'xp_reward'      => 100,
                'icon'           => 'ShieldCheck',
                'required_count' => 1,
            ],
            [
                'slug'           => 'budget_created',
                'title'          => 'Pengendali Anggaran',
                'description'    => 'Buat minimal 3 batas anggaran kategori.',
                'category'       => 'budget',
                'tier'           => 'bronze',
                'xp_reward'      => 100,
                'icon'           => 'Award',
                'required_count' => 3,
            ],
            [
                'slug'           => 'recurring_setup',
                'title'          => 'Master Otomatisasi',
                'description'    => 'Buat setidaknya 1 jadwal transaksi rutin otomatis.',
                'category'       => 'general',
                'tier'           => 'silver',
                'xp_reward'      => 100,
                'icon'           => 'Award',
                'required_count' => 1,
            ],
            [
                'slug'           => 'tx_250',
                'title'          => 'Sultan Pembukuan',
                'description'    => 'Catat minimal 250 transaksi pengeluaran/pemasukan di MoneFin.',
                'category'       => 'transaction',
                'tier'           => 'platinum',
                'xp_reward'      => 1000,
                'icon'           => 'Zap',
                'required_count' => 250,
            ],
            [
                'slug'           => 'streak_14',
                'title'          => 'Dua Pekan Juara',
                'description'    => 'Pertahankan streak pencatatan selama 14 hari berturut-turut.',
                'category'       => 'streak',
                'tier'           => 'silver',
                'xp_reward'      => 250,
                'icon'           => 'Flame',
                'required_count' => 14,
            ],
            [
                'slug'           => 'streak_60',
                'title'          => 'Dua Bulan Membara',
                'description'    => 'Pertahankan streak pencatatan selama 60 hari tanpa terputus.',
                'category'       => 'streak',
                'tier'           => 'gold',
                'xp_reward'      => 650,
                'icon'           => 'Flame',
                'required_count' => 60,
            ],
            [
                'slug'           => 'first_split_bill',
                'title'          => 'Pahlawan Patungan',
                'description'    => 'Buat pembagian tagihan (Split Bill) pertama Anda.',
                'category'       => 'general',
                'tier'           => 'bronze',
                'xp_reward'      => 75,
                'icon'           => 'Award',
                'required_count' => 1,
            ],
            [
                'slug'           => 'split_bill_5',
                'title'          => 'Master Hangout',
                'description'    => 'Buat minimal 5 pembagian tagihan patungan bersama rekan/teman.',
                'category'       => 'general',
                'tier'           => 'silver',
                'xp_reward'      => 200,
                'icon'           => 'Award',
                'required_count' => 5,
            ],
            [
                'slug'           => 'budget_all_rounder',
                'title'          => 'Arsitek Anggaran Holistik',
                'description'    => 'Buat minimal 5 batas anggaran kategori untuk kontrol pengeluaran penuh.',
                'category'       => 'budget',
                'tier'           => 'silver',
                'xp_reward'      => 200,
                'icon'           => 'Award',
                'required_count' => 5,
            ],
            [
                'slug'           => 'savings_depositor_5',
                'title'          => 'Penabung Rutin',
                'description'    => 'Lakukan minimal 5 kali deposit ke target tabungan Anda.',
                'category'       => 'saving',
                'tier'           => 'silver',
                'xp_reward'      => 150,
                'icon'           => 'Target',
                'required_count' => 5,
            ],
            [
                'slug'           => 'savings_depositor_10',
                'title'          => 'Kolektor Tabungan Emas',
                'description'    => 'Lakukan minimal 10 kali deposit ke target tabungan Anda.',
                'category'       => 'saving',
                'tier'           => 'gold',
                'xp_reward'      => 350,
                'icon'           => 'Target',
                'required_count' => 10,
            ],
            [
                'slug'           => 'goal_completed_5',
                'title'          => 'Legenda Penakluk Impian',
                'description'    => 'Berhasil menyelesaikan 5 target tabungan impian hingga 100%.',
                'category'       => 'saving',
                'tier'           => 'platinum',
                'xp_reward'      => 800,
                'icon'           => 'Target',
                'required_count' => 5,
            ],
            [
                'slug'           => 'multi_account',
                'title'          => 'Diversifikasi Finansial',
                'description'    => 'Miliki minimal 3 akun keuangan aktif (Bank, E-Wallet, Kas).',
                'category'       => 'general',
                'tier'           => 'bronze',
                'xp_reward'      => 75,
                'icon'           => 'Award',
                'required_count' => 3,
            ],
        ];

        foreach ($achievements as $ach) {
            Achievement::updateOrCreate(['slug' => $ach['slug']], $ach);
        }

        $quests = [
            // ─── DAILY QUESTS (4) ──────────────────────────────────────────
            [
                'slug'         => 'record_daily_tx',
                'title'        => 'Catat Transaksi Hari Ini',
                'description'  => 'Catat minimal 1 pengeluaran atau pemasukan hari ini.',
                'type'         => 'daily',
                'target_type'  => 'record_transactions',
                'target_count' => 1,
                'xp_reward'    => 25,
                'is_active'    => true,
            ],
            [
                'slug'         => 'daily_income_track',
                'title'        => 'Catat Arus Kas Masuk',
                'description'  => 'Catat minimal 1 transaksi pemasukan hari ini.',
                'type'         => 'daily',
                'target_type'  => 'record_income',
                'target_count' => 1,
                'xp_reward'    => 30,
                'is_active'    => true,
            ],
            [
                'slug'         => 'daily_expense_track',
                'title'        => 'Kontrol Belanja Harian',
                'description'  => 'Catat minimal 1 transaksi pengeluaran untuk memantau pengeluaran harian.',
                'type'         => 'daily',
                'target_type'  => 'record_expense',
                'target_count' => 1,
                'xp_reward'    => 25,
                'is_active'    => true,
            ],
            [
                'slug'         => 'daily_smart_review',
                'title'        => 'Cek Analisis Finansial',
                'description'  => 'Buka menu Laporan atau Ringkasan Finansial untuk memantau kesehatan keuangan.',
                'type'         => 'daily',
                'target_type'  => 'check_analytics',
                'target_count' => 1,
                'xp_reward'    => 20,
                'is_active'    => true,
            ],

            // ─── WEEKLY QUESTS (8) ─────────────────────────────────────────
            [
                'slug'         => 'weekly_tracking_3',
                'title'        => 'Pencatat Konsisten',
                'description'  => 'Catat transaksi minimal 3 kali dalam minggu ini.',
                'type'         => 'weekly',
                'target_type'  => 'record_transactions',
                'target_count' => 3,
                'xp_reward'    => 75,
                'is_active'    => true,
            ],
            [
                'slug'         => 'weekly_tracking_7',
                'title'        => 'Pencatat Super Disiplin',
                'description'  => 'Catat total 7 transaksi dalam minggu ini untuk menjaga akurasi pembukuan.',
                'type'         => 'weekly',
                'target_type'  => 'record_transactions',
                'target_count' => 7,
                'xp_reward'    => 120,
                'is_active'    => true,
            ],
            [
                'slug'         => 'weekly_saver',
                'title'        => 'Tantangan Menabung Mingguan',
                'description'  => 'Lakukan minimal 1x deposit dana ke Target Tabungan minggu ini.',
                'type'         => 'weekly',
                'target_type'  => 'deposit_goal',
                'target_count' => 1,
                'xp_reward'    => 60,
                'is_active'    => true,
            ],
            [
                'slug'         => 'weekly_saver_double',
                'title'        => 'Akselerasi Tabungan',
                'description'  => 'Lakukan setoran ke target tabungan sebanyak 2 kali dalam sepekan.',
                'type'         => 'weekly',
                'target_type'  => 'deposit_goal',
                'target_count' => 2,
                'xp_reward'    => 100,
                'is_active'    => true,
            ],
            [
                'slug'         => 'weekly_budget_guardian',
                'title'        => 'Penjaga Batas Anggaran',
                'description'  => 'Buat atau sesuaikan alokasi batas anggaran kategori minggu ini.',
                'type'         => 'weekly',
                'target_type'  => 'create_budget',
                'target_count' => 1,
                'xp_reward'    => 70,
                'is_active'    => true,
            ],
            [
                'slug'         => 'weekly_split_bill',
                'title'        => 'Patungan Cerdas (Split Bill)',
                'description'  => 'Buat 1 kalkulasi pembagian tagihan (Split Bill) bersama teman/keluarga.',
                'type'         => 'weekly',
                'target_type'  => 'split_bill',
                'target_count' => 1,
                'xp_reward'    => 65,
                'is_active'    => true,
            ],
            [
                'slug'         => 'weekly_goal_planner',
                'title'        => 'Perencana Impian Baru',
                'description'  => 'Buat target impian baru di menu Target Tabungan.',
                'type'         => 'weekly',
                'target_type'  => 'create_goal',
                'target_count' => 1,
                'xp_reward'    => 65,
                'is_active'    => true,
            ],
            [
                'slug'         => 'weekly_budget_check',
                'title'        => 'Evaluasi Finansial Mingguan',
                'description'  => 'Kunjungi menu Laporan Finansial untuk memantau performa arus kas mingguan.',
                'type'         => 'weekly',
                'target_type'  => 'check_analytics',
                'target_count' => 1,
                'xp_reward'    => 50,
                'is_active'    => true,
            ],
        ];

        foreach ($quests as $quest) {
            FinancialQuest::updateOrCreate(['slug' => $quest['slug']], $quest);
        }
    }
}
